name: lorem_ipsum
description: It is a package to generate random text easily, quickly and dynamically.
ersion: 0.0.2
homepage: https://damianrc.com
repository: https://github.com/DamianRincon/lorem_ipsum

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
